### ISSUE TITLE
Make text styles available in CSS and JS

### ISSUE THREAD

**Issue by acstll** [telekom/design-tokens#108]
They're used in the Data Grid component: https://github.com/telekom/scale/blob/main/packages/components/src/components/data-grid/data-grid.css#L14-L67

**Comment by acstll** [comment]
@lukasoppermann let's get back to this after the release 🙏

**Comment by lukasoppermann** [comment]
Yes, we need to discuss this.

I am still in favour of using the font property as this allows us to have one variable with all definitions.
