### ISSUE TITLE
Color token sketch matching

### ISSUE THREAD

**Issue by lukasoppermann** [telekom/design-tokens#148]
Trying to easy the update:

old token | new token
---|---
primary | primary / standard
primaryHover | primary / hovered
primaryActive | primary / pressed
**Misc** |  
white | text & icon / white / standard
black | text & icon / black / standard
focus | functional / focus
**Backgrounds** |  
background / background standard | background / canvas
background / background light | background / canvas subtle
background / background overlay | background / backdrop
background / background disabled | ui / solid / disabled
background / background darker | ui / solid / standard
background / background Error | functional / danger / standard
background / background Success | functional / success / standard
**Text** |  
text / text standard | text & icon / standard
text / text additional | text & icon / additional
text / text disabled | text & icon / disabled
text / text error | text & icon / functional / danger
text / text success | text & icon / functional / success
text / text info | text & icon / functional / informational
text / text link | text & icon / link / standard
text / text linkHover | text & icon / link / hovered
text / text linkVisited | text & icon / link / visited
text / text linkActive | text & icon / link / active
**Functional** |  
~functional / functional red~ | ~functional / danger / standard~ already matched with background error
~functional / functional green~ | ~functional / success / standard~ already matched with background success
functional / functional blue | functional / interactive / standard
**Additional** |  
**Important:** | Number system changed, so match `0 -> 0`, `10 -> 100`, `20 -> 200`, ...
Clay | Brown
Olive | Olive
Teal | Teal
Rose | Pink
Pigeon | Violet
Lilac | Purple

**Comment by acstll** [comment]
## uuids in legacy file

We need to replace the uuids of the tokens in [the above table](https://github.com/telekom/design-tokens/issues/148#issue-1147994771) using the following uuids:

Swatch Name | UUID (do_objectID)
--- | ---
Primary | 0c3cc007-8ae6-43a4-847d-edba2cd3612c
Black | 30527e43-938c-4a9e-8fb1-64f90192d483
White | 4ab6a51d-37de-4f97-83a1-2fc1ae58088f
Grey / Grey 0 | ef6817be-a844-45b6-8886-50faaeca6c42
Grey / Grey 10 | 35c2aff0-7d97-4d57-a503-615c33d064d7
Grey / Grey 20 | fcbe5c7b-b679-40c5-b170-f5f26a7ad2fa
Grey / Grey 30 | a138160b-4578-42e8-8d24-40b5a829bc51
Grey / Grey 40 | e579a660-be7c-44d4-800c-8572e10d9cc0
Grey / Grey 50 | 646cb8e5-c976-4feb-b4f7-2b645b731b05
Grey / Grey 60 | 2afd8531-8f92-4e18-9d55-7c781db183cf
Grey / Grey 70 | 90f96b4e-9370-4487-aed0-e1ed049e24a3
Grey / Grey 80 | ad731781-78d1-4307-aed3-a654f3b8bbd5
Grey / Grey 90 | 1409ed63-5687-42bc-b721-e535dd0734e8
Grey / Grey 100 | 919addbe-8fed-4bde-9680-e50f3ae2b382
Orange / Orange 0 | f9b8f5d1-7a25-442a-9669-bf54a025ede7
Orange / Orange 10 | d12d50f7-ce42-41cf-bf4b-2ba1f6167e37
Orange / Orange 20 | 8e32adbc-26b1-4d42-8e09-cada550a8f8c
Orange / Orange 30 | de6add85-d55c-4eb2-80c9-6396b32c60b9
Orange / Orange 40 | 77d17c86-44b4-48a7-8460-6e9e07f4b16e
Orange / Orange 50 | e8f53688-a5cc-460c-82d4-d2a6bc05408c
Orange / Orange 60 | 3200f06a-33da-423e-ae58-63db7da04760
Orange / Orange 70 | 8630a03b-397b-4995-beb0-0be900c8c4c4
Orange / Orange 80 | 8f4a2b63-5a14-4ff2-a969-1110afddcb73
Orange / Orange 90 | 608d9458-7334-46f5-b5ea-2fb70aba982e
Orange / Orange 100 | c6dddffd-650e-4de4-963c-b87118c4cc57
Red / Red 0 | 8a46dcde-6ea3-40dd-a1a3-82937df85a0e
Red / Red 10 | f27e508b-a19e-4382-9dd2-40bcc3cd0380
Red / Red 20 | 968f1f1c-7300-4fb8-a965-55c30b8e597f
Red / Red 30 | 38dca4a5-e43e-42fa-bd7a-5560d7a87b65
Red / Red 40 | 54530cd2-d8c6-4f8d-b74b-e5379014f5e2
Red / Red 50 | 174a19bc-4dc0-4f6a-aad2-0811060eec67
Red / Red 60 | 7d0bf877-7d0c-4eba-9e13-f5272d9a38f2
Red / Red 70 | ff7dcd70-73b8-45de-a00c-c4a3869957ba
Red / Red 80 | eac80f6a-66dd-4bae-8644-c1d1e84d70d0
Red / Red 90 | dc6c3281-e6dd-4c23-8105-bcb36070e47d
Red / Red 100 | c5778630-c157-4c04-b2ab-8650ef28ccf4
Blue / Blue 0 | ceb2be4d-d75a-4f40-be02-22abe745a19f
Blue / Blue 10 | afd32185-d72b-4a4a-bb8e-e14e2908a942
Blue / Blue 20 | 512ed233-0076-4304-b1cb-77594a9ef7f9
Blue / Blue 30 | b5ea4e91-8277-4901-8bf2-35eb2a1984c0
Blue / Blue 40 | b0e5d770-d208-4c27-84aa-863726115779
Blue / Blue 50 | 9b364ac6-cfcc-4e1e-8b42-a56560ce82aa
Blue / Blue 60 | 028c9ac6-741f-4187-930f-93239440270b
Blue / Blue 70 | a29750c0-8ca2-4120-8272-bde56a47e153
Blue / Blue 80 | f7ef2f57-749e-4dbe-b845-ae104fcf5676
Blue / Blue 90 | 5a5ac611-4696-4279-8b9a-34e395355449
Blue / Blue 100 | 6af30311-2536-4253-8fc0-2ce474d2ace6
Teal / Teal 0 | 63e84e16-2b0c-4c4c-9bf3-8f2a093e4545
Teal / Teal 10 | 408f1f42-ceb1-41bb-8790-15f3f651c730
Teal / Teal 20 | 75c9f94b-7755-4d5c-a375-180e27be5dfe
Teal / Teal 30 | 2fbd8e05-0769-40bb-afa5-8f5dde157741
Teal / Teal 40 | 798335df-efdb-43f6-a85a-be7f2ee6ed78
Teal / Teal 50 | 6e227cc2-b361-4a99-b7e0-b5abdae0a6ae
Teal / Teal 60 | ab8703c8-f9e0-4b82-b5a9-2df190401ea4
Teal / Teal 70 | 13235f46-4623-44ef-903a-2dd85c6fe7dc
Teal / Teal 80 | 6598d7a0-0b7f-4bdf-9358-22fa37955d7a
Teal / Teal 90 | a153480f-3637-4b23-a479-4004b467af5b
Teal / Teal 100 | e4cea5ce-ed93-47e4-8891-a30948e44fef
Green / Green 0 | b9992ebc-1db0-4a21-8b56-b3e5fe88387e
Green / Green 10 | 63b7e1e0-9c71-48e2-9ce1-82442891ce5b
Green / Green 20 | 9218deed-a746-46a8-84e8-3a739af020c9
Green / Green 30 | a5af2eea-4ce4-4384-9df9-244200ff9c30
Green / Green 40 | 273f83cf-4e14-42e0-afc8-4b4b0e1375b9
Green / Green 50 | e2f55a82-e17c-4035-9e77-706d80bb7b77
Green / Green 60 | ee7f90b5-de8f-4449-94ba-f807bde1c1b5
Green / Green 70 | b701a7f6-82a5-40d1-8a9c-87951669aef9
Green / Green 80 | 7383c2c1-10a2-404b-a8f4-1ba3fe828c5f
Green / Green 90 | d4ec7813-4f43-4dcb-a8ef-adc3abebbf40
Green / Green 100 | f9c80ee4-693e-4c80-8e74-071cebea9f4d
Clay / Clay 0 | 8cc0293d-d5af-4f03-9a3e-39854f44cfd5
Clay / Clay 10 | da8242e6-1fef-4991-8070-1a28ff653471
Clay / Clay 20 | 40f1484b-df53-4552-a8cb-5edf49f4917d
Clay / Clay 30 | 04d02152-50dc-4215-85ad-03f2c70c1d27
Clay / Clay 40 | 0c573402-e2fd-476a-b2d5-3d8969487078
Clay / Clay 50 | bc0a421c-76de-4e1f-92e5-ec26fd137b3d
Clay / Clay 60 | 2c2e3743-ad2e-4042-863d-159d77b7be23
Clay / Clay 70 | 90e43048-40cd-47b8-a39a-a7f79c704544
Clay / Clay 80 | 5c63aa9c-4c9c-4230-8d17-1613799154ec
Clay / Clay 90 | c9048f2d-e2b7-44e7-81ce-2f09059244d1
Clay / Clay 100 | c3230be9-c6af-4fa5-8ff6-252169610a49
Rose / Rose 0 | 1bac47a3-3778-4853-bd92-cc00b010c12c
Rose / Rose 10 | 340f1c22-dbbc-4467-b4a8-cc5003e6fd9f
Rose / Rose 20 | f989814d-1fe5-40bf-af18-0384320114dc
Rose / Rose 30 | fb4accdb-e4a8-454a-be8e-53800d156526
Rose / Rose 40 | a1826992-1f16-430f-a23d-94df89d2ece7
Rose / Rose 50 | d1d4e348-4a4f-41cc-b270-35cf266fb390
Rose / Rose 60 | 243aaa54-9a38-440c-b6e3-af1a9b651fea
Rose / Rose 70 | 49058a1b-55f1-4b19-b17b-009ed332a5c7
Rose / Rose 80 | 2fe93fa5-5038-46f6-9bb6-611bc53b9fe3
Rose / Rose 90 | aa6495cf-d492-4c2a-8658-921bec129809
Rose / Rose 100 | 7154405b-1651-41ef-aa27-52cd79a103c0
Lilac / Lilac 0 | bb1258aa-b05a-41bb-b742-0c4eb71986e4
Lilac / Lilac 10 | 9cb6b92f-7dd4-478b-8972-7256ee6ced78
Lilac / Lilac 20 | d1652be4-4efb-478f-9ed6-0b761d860f87
Lilac / Lilac 30 | afebba26-26ca-4bba-bd7d-7f6df45e7fc0
Lilac / Lilac 40 | 4f45fcdd-d5b6-4212-8eeb-36807eb3a218
Lilac / Lilac 50 | d57a3882-f75e-4c72-b65a-bc91035d11c7
Lilac / Lilac 60 | 245c17bd-41ff-410d-b532-0cea51d17bfa
Lilac / Lilac 70 | 885c72f4-9135-444d-9062-02fd16e7da93
Lilac / Lilac 80 | 20719811-b665-432a-9512-97ca06a229d7
Lilac / Lilac 90 | d117354b-39ad-4493-916e-cd958408bd9c
Lilac / Lilac 100 | 4e9b45f6-d256-4863-b073-c98ebc8d51ef
Pigeon / Pigeon 0 | 23644991-2162-4588-8b9a-5197ae3ddf42
Pigeon / Pigeon 10 | d8aec0f4-b94c-44d4-8357-62337b8826a6
Pigeon / Pigeon 20 | 0192b8b3-87a5-4f3d-a8ff-1b6c7b25c57b
Pigeon / Pigeon 30 | 52e6f5dc-ca6c-46cc-8f55-bcffa37a1f13
Pigeon / Pigeon 40 | 42142f0a-3d6a-4848-a585-bda2b40ae743
Pigeon / Pigeon 50 | 74b4c946-22f2-4574-8666-cddca8072c79
Pigeon / Pigeon 60 | 453f1b26-29ac-44f5-9168-edc42bd8eceb
Pigeon / Pigeon 70 | 2b6fab1b-febc-4590-8eb8-238267cf8452
Pigeon / Pigeon 80 | cbd0fa96-6492-407c-98e0-c7976bf9e477
Pigeon / Pigeon 90 | 423b4389-7c54-4787-81a0-d979ba9acd73
Pigeon / Pigeon 100 | 18074bfb-2a0e-489e-8b70-4c3f5efa330a
Neptune / Neptune 0 | 23a5c891-a033-4108-9bcf-f0d51ee694db
Neptune / Neptune 10 | b3ea2214-94b3-4e34-bc15-b1e7a8d0a111
Neptune / Neptune 20 | 42e36e67-567f-4d2c-af63-ff5803c8cf4d
Neptune / Neptune 30 | d942fc80-a7c1-49da-bd49-990f645eccf7
Neptune / Neptune 40 | 499abb4e-069c-4034-ae5b-d96af76849b8
Neptune / Neptune 50 | a37a5866-efe8-4444-ba58-4a7357ca1d5a
Neptune / Neptune 60 | fa00bcc5-c2ea-457b-a015-8b295a3e7db3
Neptune / Neptune 70 | 57c852b8-0f82-4145-b22a-086d5274f8d4
Neptune / Neptune 80 | 5095bc79-7bc0-49dd-8c46-a734c3a88cf4
Neptune / Neptune 90 | 3df72b8d-9086-4df1-9bdc-5225e58b15e6
Neptune / Neptune 100 | 5c5ac2a0-af03-4d5d-a6c2-e9867c0d552d
Olive / Olive 0 | d3500782-cf8d-49dc-8ddf-de424a851f49
Olive / Olive 10 | c4ca187e-48b2-445d-98b3-4de13672ec96
Olive / Olive 20 | e975b2de-4dc2-4159-b3b2-9f563a4dd135
Olive / Olive 30 | f20fd99b-8652-4e41-92d0-c5d9ddabbdab
Olive / Olive 40 | 610d0d0b-ee38-407c-b198-4438eabe4e02
Olive / Olive 50 | 13d55a31-719b-472d-ae4a-9e3fac706ba8
Olive / Olive 60 | ae5d0116-9b66-473c-819e-41488d9f558d
Olive / Olive 70 | 70307965-91d5-43ad-bd9b-a918039aa093
Olive / Olive 80 | 30796e87-4fe4-4408-9cd9-c30e7a89592f
Olive / Olive 90 | 3471faf2-583d-429a-beef-5c9da06c73ae
Olive / Olive 100 | f082d35d-afbe-4bba-9275-d4aa14e5f302
PrimaryHover | e1536366-bc18-4c23-92b4-3f575537d29d
PrimaryActive | 78294714-f89c-4602-98f4-388fe7d978e7
Focus | 273d0b72-625b-43a0-8705-666f84d384b3
Text / Text Standard | 490fee2e-40f5-4341-9d23-0b99b8cc533d
Text / Text Additional | fb10e82d-f095-4d43-82ff-22ef8cbea7fa
Text / Text Link | c36b0903-2b5c-40cd-a98b-5b4fa16336d9
Text / Text LinkHover | 9d55a56e-ffef-499a-9fc0-88ae8743059a
Text / Text LinkActive | 4f95d3a7-9001-401f-9dfb-0e1db8b83362
Text / Text LinkVisited | 1fe5cc61-6388-4fbc-bd8f-128b65cac9d4
Text / Text Info | 88bd46e1-03a6-48c0-9a91-83a5b59c12c6
Text / Text Disabled | 5dd2f46f-a035-4fbe-94e7-f59f44a944a6
Text / Text Success | bce2d347-b4a7-418b-bf68-8cd71aac383e
Text / Text Error | d0afb71d-852f-4ff2-b3fa-e9ffbd1e9875
Background / Background Standard | 21e9e92a-699d-4493-b2c5-37ef1f7298e4
Background / Background Light | 6a6f7ef4-9457-48dc-abcb-c528453050f2
Background / Background Darker | fd4ee003-9fc9-4139-8e19-a27c81c8ff28
Background / Background Overlay | 1a8a7a7d-eb33-4cea-81c5-96d8bbb8959c
Background / Background Disabled | 6cbe35fb-cd62-4964-9737-6c25720acf30
Background / Background Success | bb8b0e06-b158-486a-b7fb-c654c09e581e
Background / Background Error | c9d60166-646a-46ca-8295-26184a9f7fcc
Functional / Functional Red | 9eedeaae-e01e-424e-a8e1-909d23907595
Functional / Functional Green | fbaefc08-79ff-4300-9a28-c7ff492a7bf6
Functional / Functional Blue | 664e12db-9c0b-4104-89bb-a18850ce6c95
