### ISSUE TITLE
Matching text styles

### ISSUE THREAD

**Issue by lukasoppermann** [telekom/design-tokens#149]
old text styles | new text styles
--- | ---
H1_TeleNeo_191919 | Heading 1
H2_TeleNeo_191919 | Heading 2
H3_TeleNeo_191919 | Heading 3
H4_TeleNeo_191919 | Heading 4
H5_TeleNeo_191919 | Heading 5
H6_TeleNeo_191919 | Heading 6
**Copy** | 
~Body_Large_Bold_191919~ | n/a
~Body_Large_Medium_191919~ | n/a
Body_Large_Regular_191919 | Callout
Body_Short_Medium_191919 | UI
Body_Short_Bold_191919 | UI Bold
Body_Long_Regular_191919 | Body
Body_Long_Bold_191919 | Body Bold

**Comment by acstll** [comment]
## uuids in legacy file

We need to ~~replace~~ add the uuids of the tokens in [the table above](https://github.com/telekom/design-tokens/issues/149#issue-1149043530) using the following uuids:

Ignore the ones not in the table above!

Text Style Name | UUID (do_objectID)
--- | ---
Light/12_16_TeleNeo_Bold_007DB3 | ED548ACD-841A-4D6F-93A2-99B0699D82E5
Light/16_20_TeleNeo_Medium_6C6C6C | 5347EA85-D397-4222-BFB3-DB66DB46EB95
Light/16_24_TeleNeo_Medium_007DB3 | BADC4517-AB10-4F38-ABFC-54E6608A464B
Light/16_24_TeleNeo_Bold_FFFFFF | 78CCBB80-1585-4662-AB43-7CF1B91A6787
Light/12_20_TeleNeo_Bold_FFFFFF | 33EC13F2-4756-49D0-BC32-2D3740850AD6
Light/10_12_TeleNeo_Bold_6C6C6C | DE77A418-8698-48FA-8C82-EC9CAD17D4B7
Light/16_20_TeleNeo_Medium_262626 | 592C6107-FF9B-4DA2-81E0-CCCBCD78BDF7
Light/12_16_TeleNeo_Bold_D90000 | A8632702-F178-4A65-9909-1492F5938267
Light/12_16_TeleNeo_Bold_FFFFFF | F1ED477B-764B-4481-8542-7759A0F32FEB
Light/16_24_TeleNeo_Medium_00739F | E37583B0-F4CA-4437-8E0B-F95CB7E9C4A5
Light/12_16_TeleNeo_ExtraBold_262626 | 723B41AB-EF75-4BED-A0B7-F29F70A9B874
Light/12_16_TeleNeo_Bold_262626 | B9D57664-3400-417D-96D0-8A26A5682151
Light/48_56_TeleNeo_ExtraBold_262626 | CD38A931-3D7C-47A9-8572-FE044BEEE346
Light/24_32_TeleNeo_ExtraBold_262626 | 3F8136C9-48F6-42A6-B3CD-E7AA0D82C4A1
Light/16_24_TeleNeo_Bold_6B6B6B | 83F202FF-2A68-4106-9925-107CDAEC5129
Light/48_56_TeleNeo_ExtraBold_262626 | 554149FF-6062-41FE-954F-B83FEDDD7DB7
Light/16_24_TeleNeo_Bold_262626 | 9FE1CEAF-FE1F-4C44-A24F-10C30F90EA67
Light/24_32_TeleNeo_ExtraBold_262626 | AF7111DB-4390-4837-B519-4C8F4EA8DE7D
Light/12_16_TeleNeo_Bold_262626 | 028A400A-859C-4688-847A-255A5FE00F6A
Light/16_24_TeleNeo_Medium_009DE0 | 19DCFEB1-DCDD-4385-8096-F85C30E63FA4
Light/32_40_TeleNeo_Extrabold_262626 | 8F1B8725-C47C-4CEE-B089-24BD6AA8387F
Light/16_24_TeleNeo_Bold_FFFFFF | 67675490-3E58-4730-B423-E8D0349E65EC
Light/16_24_TeleNeo_Bold_6B6B6B | AF786069-627D-4811-8F05-1E86F19D0586
01 Body_Long_TeleNeo_Medium_191919 | 000A0807-6A99-4F1E-8437-B590BE81B42C
H3_TeleNeo_191919 | 09380335-83C1-4B0B-BBAB-EE2194F83C67
H5_TeleNeo_191919 | 29E0191D-BA8D-41CE-B777-84F16EBE07CC
02 Body_Short_TeleNeo_Medium_191919 | 2E31A03E-5CDB-4495-B752-BE528887F9FA
03 Body_Large_TeleNeo_Medium_191919 | 3C6C952D-ED73-4AB2-819B-C1CA1FF80073
01 Body_Long_TeleNeo_Bold_191919 | 49D6E98C-44BF-4A65-926F-CCFE5DE97316
02 Body_Short_TeleNeo_Bold_191919 | 5952B8E0-E671-4FD7-B5E9-F7B35994A568
02 Body_Short_TeleNeo_Regular_191919 | 600568B2-3BD8-44FF-ACEC-576EC197EF80
H1_TeleNeo_191919 | 748B5B13-3227-4C2F-89BC-A2E273E6727E
01 Body_Long_TeleNeo_Regular_191919 | 92541698-8672-4C85-AAB0-86351E764C2B
H6_TeleNeo_191919 | 96B71BB7-4924-450B-A090-42C83C066BB1
03 Body_Large_TeleNeo_Regular_191919 | D6365CF0-2671-4374-BD8E-6E1C2D2D29BF
H4_TeleNeo_191919 | DCA48C57-DA5C-4B2A-825F-82C7E28955FD
03 Body_Large_TeleNeo_Bold_191919 | EBE18869-0D16-499C-8063-B07A254B0481
H2_TeleNeo_191919 | F40BF846-4438-4B29-BADD-1A536C109E73
